name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages # Assuming you want to deploy to the gh-pages branch

      - name: Set Git token
        run: |
          git config --global user.name 'robindfernandes'
          git config --global user.email 'robindfernandes@gmail.com'
          git config --global user.email "gh-pages-token@users.noreply.github.com"
          git config --global user.token ${{ secrets.GH_PAGES_TOKEN }}

      - name: Copy built files to deployment directory
        run: |
          mkdir -p docs
          cp -r .next/* docs/

      - name: Deploy to GitHub Pages
        run: |
          npm run build
          mkdir -p docs
          cp -r .next/* docs/
        env:
          NODE_ENV: production
