name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages # Assuming you want to deploy to the gh-pages branch
      - name: Commit and push changes
        run: git config --robindfernandes ${{ secrets.GH_PAGES_TOKEN }}
          git config --robindfernandes@gmail.com ${{ secrets.GH_PAGES_TOKEN }}@users.noreply.github.com
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages # Change 'gh-pages' to the target branch name
