name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Git token
        run: |
          git config --global user.name 'robindfernandes'
          git config --global user.email 'robindfernandes@gmail.com'
          git config --global user.token ${{ secrets.GH_PAGES_TOKEN }}

      - name: List contents before copy
        run: ls

      - name: Copy built files to deployment directory
        run: cp -r docs/* .

      - name: List contents after copy
        run: ls

        
